### ISSUE TITLE
Cannot handle magic commands

### ISSUE THREAD

**Issue by lihongchun2007** [ipython/ipynb#27] opened 2017-01-06 08:23 UTC
When cells in a notebook contain magic commands, ipynb cannot import the notebook.

For example, a cell in a notebook contains `%matplotlib inline`. To import this notebook, ipynb throws an exception, `SyntaxError: invalid syntax`.

**Comment by Carreau** [comment] 2017-01-06 09:34
It is a know issue see #6 and it is partly on purpose as magics need IPython to be runnign to work which might not be the case.

All magics are often just syntactic sugar around pure python code, so when that's the case you can replace them by their equivalent.

Closing as duplicate of #6

**Closed by Carreau** 2017-01-06 09:34 UTC
